# Generated by Django 4.2 on 2023-04-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_customuser_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
