# Generated by Django 4.2 on 2023-04-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatefood',
            name='user',
        ),
    ]
