# Generated by Django 4.2 on 2023-05-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doner', '0002_remove_donatefood_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateFoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('donor_type', models.CharField(choices=[('Hotel', 'Hotel'), ('Catering', 'catering'), ('Hostels', 'Hostels'), ('Normal user', 'Normal user')], max_length=100)),
                ('donor_discription', models.CharField(max_length=100)),
                ('food_type', models.CharField(choices=[('veg', 'veg'), ('Nonveg', 'Nonveg'), ('Both', 'Both')], max_length=100)),
                ('food', models.CharField(choices=[('biriyani', 'biriyani'), ('rice', 'rice'), ('porota curry', 'porota curry'), ('puttu curry', 'puttu curry')], max_length=100)),
                ('food_discription', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='DonateFood',
        ),
    ]
