# Generated by Django 4.2 on 2023-05-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doner', '0003_donatefoodmodel_delete_donatefood'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
    ]
