# Generated by Django 4.1.7 on 2023-06-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('count', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('request_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('contact_information', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='DonateFood',
        ),
    ]
