# Generated by Django 4.1.7 on 2023-06-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_requestdonation_delete_donatefood'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(max_length=120)),
                ('donor_type', models.CharField(max_length=100)),
                ('donor_discription', models.CharField(max_length=100)),
                ('food_type', models.CharField(max_length=100)),
                ('food', models.CharField(max_length=100)),
                ('food_discription', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=120)),
                ('count', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('contact_information', models.CharField(max_length=100)),
            ],
        ),
    ]
